version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  slack: circleci/slack@3.4.2

jobs:
  lint-dockerfiles:
    executor: docker/machine
    steps: 
      - checkout
      - docker/dockerlint:
          dockerfile: nginx/Dockerfile

  build-and-push-cicd:
    executor: docker/machine
    steps:
      - checkout
      - docker/check:
          docker-username: quay_username
          docker-password: quay_userpass
          registry: quay.io
      - docker/build:
          image: 15five/redash-nginx
          tag: latest
          registry: quay.io
          path: nginx
      - docker/push:
          digest-path: /tmp/digest.txt
          image: 15five/redash-nginx
          tag: latest
          registry: quay.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - slack/status:
          channel: devops-releases

workflows:
  nginx:
    jobs:
      - lint-dockerfiles
      - build-and-push-cicd:
          requires:
            - lint-dockerfiles
          filters:
            branches:
              only:
                - main

  nginx-scheduled:
    jobs:
      - build-and-push-cicd
    triggers:
      - schedule:
         cron: "0 2 1 * *"
         filters:
           branches:
             only:
               - main